public enum E_FragmentIndex
{
    PLACEMENT_1,
    PLACEMENT_2,
    PLACEMENT_3,
    PLACEMENT_4,
    PLACEMENT_5,
    PLACEMENT_6,
    PLACEMENT_7,
    PLACEMENT_8,
    PLACEMENT_9,
    PLACEMENT_10
}
